apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: icqrsn9bs-go
  janus-idp.io/tekton: icqrsn9bs-go
  backstage.io/kubernetes-id: icqrsn9bs-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: icqrsn9bs-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
